import NavD from '@/components/Header/NavD'
import './globals.css'
import { Inter, Poppins } from 'next/font/google'
import Footer from '@/components/Footer/Footer'

const poppins = Poppins({ subsets: ['latin'], weight:['100','200','500','800'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavD/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
